version: '3.8'

services:
  mariadb:
    image: mariadb:10.11
    container_name: billetterie-mariadb
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: billetterie
      MYSQL_USER: billetterie_user
      MYSQL_PASSWORD: billetterie_password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    container_name: node
    build: ./backend
    ports:
      - "3000:3000" 
    depends_on:
      - mariadb
    environment:
      - NODE_ENV=development
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_NAME=billetterie
      - DB_USER=billetterie_user
      - DB_PASSWORD=billetterie_password
      - PORT=3000
      - JWT_SECRET=your-super-secret-jwt-key-here-change-in-production
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./uploads:/app/uploads
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    container_name: react
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
      - REACT_APP_API_URL=http://localhost:3000 
    networks:
      - app-network
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mariadb_data:

networks:
  app-network:
    driver: bridge
